name: 'Sandbox Flutter Lint'

on:
  push:
    branches:
      - main

jobs:
  app-lints:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: fpg-wb
        working-directory: ./widgetbook
        run: flutter pub get

      - name: Analyze Tools wb
        uses: zgosalvez/github-actions-analyze-dart@v1
        with:
          fail-on-warnings: true
          working-directory: ./widgetbook

      - name: Format Tools wb
        working-directory: ./widgetbook
        run: dart format . --set-exit-if-changed

      - name: FPG Main
        run: flutter pub get

      - name: Analyze App
        uses: zgosalvez/github-actions-analyze-dart@v1
        with:
          fail-on-warnings: true

      - name: Format App
        run: dart format . --set-exit-if-changed

